name: Build & Deploy Resume PDF

on:
  push:
    paths:
      - 'resume/**'
      - '_pages/**'
      - '.github/workflows/deploy_resume.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run Python script to generate resume.tex
        run: python3 resume/scripts/generate_tex.py

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra

      - name: Compile LaTeX resume
        working-directory: resume
        run: pdflatex resume.tex

      - name: Commit and push updated resume.pdf
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add resume/resume.pdf
          git commit -m "Auto-update resume.pdf from Actions"
          git push
        continue-on-error: true