name: Build Resume

on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:full  # ✅ 含 pdflatex 和 python3+pip3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python deps
        run: pip3 install pyyaml

      - name: Generate resume.tex
        run: python3 resume/scripts/generate_tex.py

      - name: Compile LaTeX resume
        working-directory: resume
        run: pdflatex resume.tex

      - name: Move PDF to docs/
        run: |
          mkdir -p docs
          cp resume/resume.pdf docs/resume.pdf

      - name: Commit to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add docs/resume.pdf
          git commit -m "update resume.pdf"
          git push
        continue-on-error: true