name: Build Resume

on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install pyyaml
      - run: python3 resume/scripts/generate_tex.py
      - run: pdflatex resume/resume.tex
      - run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add resume.pdf
          git commit -m "update pdf"
          git push
        continue-on-error: true