name: Build Resume

on:
  push:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-extra
          pip install pyyaml

      - name: Generate resume.tex
        run: python3 resume/scripts/generate_tex.py

      - name: Compile LaTeX resume
        run: pdflatex resume/resume.tex

      - name: Commit updated PDF
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add -f resume.pdf
          git commit -m "update resume.pdf"
          git push
        continue-on-error: true